name: 'JIRA Issue Create Action'
description: 'Create JIRA Issue'
inputs:
  jira-api-host:
    description: 'JIRA API Host'
    required: true
  jira-api-user:
    description: 'JIRA API User'
    required: true
  jira-api-token:
    description: 'JIRA API Token'
    required: true
  body:
    description: 'JIRA Issue Body JSON String'
    required: true
outputs:
  result:
    description: 'API Response JSON String'
runs:
  using: 'node12'
  main: 'dist/index.js'

